apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bps8qpdjx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bps8qpdjx-nodejs 
  name: bps8qpdjx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bps8qpdjx-nodejs 
